import genAI from "../config/geminiConfig.js";
import {
  safeJSONParse,
  sanitizeAIOutput,
} from "../utils/gemini/quizSanitizer.js";
import { buildQuizPrompt } from "../utils/gemini/quizPromptBuilder.js";

const sleep = (ms) => new Promise((res) => setTimeout(res, ms));

const generateWithRetry = async (modelName, prompt, maxRetry = 3) => {
  let lastError;

  for (let attempt = 1; attempt <= maxRetry; attempt++) {
    try {
      const model = genAI.getGenerativeModel({ model: modelName });
      return await model.generateContent(prompt);
    } catch (err) {
      lastError = err;


      if (err?.status === 503 && attempt < maxRetry) {
        console.warn(
          `Gemini (${modelName}) overloaded. Retry ${attempt}/${maxRetry}...`
        );
        await sleep(1000 * attempt);
      } else {
        throw err;
      }
    }
  }

  throw lastError;
};


export const generateQuizFromContent = async (
  htmlContent,
  count = 3,
  level = 1
) => {
  try {
    const MAX_CHARS = 8000;
    const trimmedContent =
      typeof htmlContent === "string" ? htmlContent.slice(0, MAX_CHARS) : "";

    const prompt = buildQuizPrompt(trimmedContent, count, level);

    let result;
    try {
      result = await generateWithRetry("gemini-2.5-pro", prompt, 3);
    } catch (err) {
      console.warn("Falling back to flash model...", err.message);
      result = await generateWithRetry("gemini-2.5-flash", prompt, 2);
    }

    const rawOutput = result?.response?.text() || "";

    const sanitizedOutput = sanitizeAIOutput(rawOutput);
    const parsedJSON = safeJSONParse(sanitizedOutput);

    if (!parsedJSON) {
      throw new Error("Invalid JSON generated by Gemini");
    }

    return parsedJSON;
  } catch (err) {
    console.error("Error in generateQuizFromContent:", err);

    if (err?.status === 503) {
      throw new Error("AI sedang sibuk, silakan coba lagi beberapa saat");
    }

    throw new Error("Failed to generate quiz from Gemini API");
  }
};
